prettiness

diff --git a/src/optspec b/src/optspec
--- a/src/optspec
+++ b/src/optspec
@@ -1,18 +1,20 @@
 #!/bin/bash
-
 shopt -qs expand_aliases
 
-alias optspec='declare -a args;
-               declare -A opts; 
-               optspec_fn ${#} ${@}'
 
+alias optspec=$(echo 'declare -a args; '        \
+                     'declare -A opts; '        \
+                     '__optspec_fn ${#} ${@} ' )
 
-function optspec_fn() {
+__optspec_fn ()
+{
   if [ -n "${1//[0-9]}" ] || (( ${#} - ${1} - 2 )); then
-    echo "error: optspec should be invoked via the alias defined "\
-         "in ${shell_lib_dir}/optspec"  1>&2
-    return 1  
+    echo -e 1>&2 "error: __optspec_fn is not part of a public API."         \\n\
+                 "For details, see the file 'src/optspec\` in your shell-lib"  \
+                 "installation directory."
+    return 1
   fi
+
   local param=1
   local specs=${!#//,/ }
   local matched spec
@@ -30,7 +32,7 @@ function optspec_fn() {
         if [ "${dif}" != ${!param} ]; then           # match: remaining != original
           matched=1
 
-          if [ -z "${spec#*:}" ]; then               # arg-required spec ('*:') 
+          if [ -z "${spec#*:}" ]; then               # arg-required spec ('*:')
             if [ -z "${dif}" ]; then                 # no trailing chars supplied: (arg opt)
               let param++                              # (assume next param is arg)
               dif=${!param}
@@ -48,18 +50,16 @@ function optspec_fn() {
       done
 
     fi
-    (( matched )) ||  args[${#args[@]}]="${!param}"  # no matching spec: non-opt param 
+    (( matched )) ||  args[${#args[@]}]="${!param}"  # no matching spec: non-opt param
   done
+}
 
- }
 
-
-if [ ${0##*/} = "optspec" ]; then                    # handle script mode
+if [[ $0 == *optspec* ]]; then                       # handle script mode
   spec=${!#}
   set - "${@:1:${#}-1}"
   optspec "${spec}"
 
   echo ${args[@]@A}                                  # print assignable form to outer scope
   echo ${opts[@]@A}
-  
 fi
